### ISSUE TITLE
Open source code for training

### ISSUE THREAD

**Issue by Williamwsk** [aipixel/E2E-HIM#1]
When will you plan to open source the training code? Model Time-consuming Have you tested the code you implemented this time? Can real-time reasoning be achieved? Looking forward to your reply！

**Comment by QLYoo** [comment]
Due to the commercial value of the method, we only provide demo inference code and do not intend to release the training code. The model has been refined, and its performance is slightly better than the model mentioned in the paper, with efficiency comparable to it.  If you use a high-end GPU solely to executing this model, real-time inference may be achieved. We will explore better solutions for commercial purposes in the future. Thank you for your interest. Have a nice day.
